name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: Bret06/Omegacraft-Season-4-Resource-Pack
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "Bret06"
        git config --global user.email "bretholloway06@gmail.com"
        git config pull.rebase false
        git pull
        rm -f release.zip
    - name: Archive Release
      uses: Bret06/Omegacraft-Season-4-Resource-Pack
      with:
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force